# Generated by Django 5.0.4 on 2024-04-12 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_document1_document2_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document1',
            name='user_id',
            field=models.CharField(default=datetime.datetime(2024, 4, 12, 10, 2, 12, 171068, tzinfo=datetime.timezone.utc), max_length=234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document2',
            name='user_id',
            field=models.CharField(default=datetime.datetime(2024, 4, 12, 10, 2, 18, 889646, tzinfo=datetime.timezone.utc), max_length=234),
            preserve_default=False,
        ),
    ]
