# Generated by Django 5.0.4 on 2024-04-17 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_document1_user_id_document2_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fields_count', models.IntegerField()),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=100)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.documenttype')),
            ],
        ),
        migrations.CreateModel(
            name='User_tg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Document1',
        ),
        migrations.DeleteModel(
            name='Document2',
        ),
    ]
