# Generated by Django 5.0.4 on 2024-04-17 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_documenttype_documenttypefield_user_tg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocumentFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.documenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.user_tg')),
            ],
        ),
    ]
