# Generated by Django 5.0.4 on 2024-04-19 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_userdocumentfill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttypefield',
            old_name='name',
            new_name='field_name',
        ),
        migrations.AddField(
            model_name='userdocumentfill',
            name='filled_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='user_documents/'),
            preserve_default=False,
        ),
    ]
