# Generated by Django 4.2.3 on 2024-04-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_rename_name_documenttypefield_field_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttypefield',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
